### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by gp-slick-coder** [mceSystems/node-windows-trayicon#2]
```
2366 verbose stack Error: windows-trayicon@1.0.2 install: `autogypi && node-gyp configure build`
2366 verbose stack Exit status 1
2366 verbose stack     at EventEmitter.<anonymous> (C:\Users\mail\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
2366 verbose stack     at EventEmitter.emit (events.js:182:13)
2366 verbose stack     at ChildProcess.<anonymous> (C:\Users\mail\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2366 verbose stack     at ChildProcess.emit (events.js:182:13)
2366 verbose stack     at maybeClose (internal/child_process.js:962:16)
2366 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
2367 verbose pkgid windows-trayicon@1.0.2
2368 verbose cwd P:\Temp\nodejs-starter
2369 verbose Windows_NT 10.0.17134
2370 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mail\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
2371 verbose node v10.15.0
2372 verbose npm  v6.4.1
2373 error code ELIFECYCLE
2374 error errno 1
2375 error windows-trayicon@1.0.2 install: `autogypi && node-gyp configure build`
2375 error Exit status 1
2376 error Failed at the windows-trayicon@1.0.2 install script.
2376 error This is probably not a problem with npm. There is likely additional logging output above.
2377 verbose exit [ 1, true ]
```

**Comment by Unforgiven-wanda** [comment]
Same issue

**Comment by mceIdo** [comment]
@Unforgiven-wanda have you tried version 2.0.0? The original issue was before a fix I applied to support node 12

**Comment by Unforgiven-wanda** [comment]
Hello again,
It seemed the issue stemmed from using Python 3.8 instead of 2.7
It works fine now.
Thank you.

And sorry for hijacking your issue @gbreeze

**Comment by mceIdo** [comment]
@gbreeze if still relevant - we just released v3.0.0 that works with N-API and confirmed to work on node 14
