### ISSUE TITLE
Can't start after exe package

### ISSUE THREAD

**Issue by phcmaia** [mceSystems/node-windows-trayicon#4]
Hello , 
Installtion works and if i run with node also works , but when package into an EXE with nexe or pkg gives the following : 

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:680:18)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/module.js:11:18)
    at initNode (C:\snapshot\test\node_modules\nbind\dist\nbind.js:141:15)
    at C:\snapshot\test\node_modules\nbind\dist\nbind.js:115:13
    at findCompiledModule (C:\snapshot\test\node_modules\nbind\dist\nbind.js:79:13)

Can you help ? 
Thanks ,

**Comment by punisher97** [comment]
You copy .node file dependecies of package in .exe folder?

**Comment by YeapGuy** [comment]
I've searched for a solution for this for multiple hours and finally found it ([here](https://github.com/vercel/pkg/issues/161)), so I thought I'd share it with you. For unknown reasons, it's only going to work when the packaged file is named node.exe. I'll continue to search for a workaround or a fix to this package so it works with .exe files named other than node.exe.

**Comment by mceIdo** [comment]
A re-write was done dropping nbind and adopting N-API, which turns this into a pretty standard module - can someone confirm if this is still an issue with v3.0.0?

**Comment by YeapGuy** [comment]
@mceIdo Nope, now I get a different error (yay?):
Error: A dynamic link library (DLL) initialization routine failed.

**Comment by YeapGuy** [comment]
And again, this only happens with a different filename than "node". Naming the file node.exe and then running it works.

**Comment by YeapGuy** [comment]
And also. I found a workaround for this issue some time ago, just forgot to put it here:
Use [rid.exe](https://www.ironsrc.com/blog/rename-import-dll/) on the .node file found in \node_modules\windows-trayicon\build\Release\addon.node. Example: `rid.exe addon.node node.exe yourfilename.exe`. That does the trick.

**Comment by alcor93** [comment]
hello,
can you please explain more how to solve the issue with pkg. It's not clear for me. thanks
